---
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ mongodb_const[ansible_os_family]['dependencies'] }}"
    state: present
    update_cache: true

- name: add mongodb repo
  block:
    - name: add gpg key
      ansible.builtin.apt_key:
        url: "{{ mongodb_const[ansible_os_family]['mongodb_gpg'] }}"
        state: present

    - name: add mongodb repo
      ansible.builtin.apt_repository:
        repo: "{{ mongodb_const[ansible_distribution]['mongodb_repo'] }}"
        state: present
  when: mongodb.repo == "mongodb"

- name: install mongodb packages
  ansible.builtin.apt:
    name: "{{ mongodb_const[ansible_os_family]['packages'] }}"
    state: present
    update_cache: true
  ignore_errors: true

- name: force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true