---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # MongoDB
      mongodb:
        enabled: true
        version: "5.0"
        repo: "mongodb"
        service:
          enabled: true
          state: "started"
      # MongoDB -> install
      mongodb_install:
        enabled: true
        packages: ["mongodb-org"]
      # MongoDB -> config
      mongodb_config:
        enabled: true
        file: "mongod.conf"
        src: "mongod_conf_{{ ansible_os_family }}.j2"
        backup: true
        data: |

  tasks:
    - name: role darexsu.mongodb
      include_role:
        name: darexsu.mongodb